config/routes.rb
Wh::Application.routes.draw do

  scope :admin do
    get 'overview' => 'dashboard#index', as: :dashboard

    resources :subscribers, only: [ :index, :destroy ]
    resources :registrants, only: [ :index, :destroy ]
    resources :organizations
    resources :users
    resources :profiles
    resources :affiliations
    resources :contacts
    resources :articles
  end

  # Blog

  get 'blog' => 'blog#index', as: :blog
  get 'blog/:slug' => 'blog#show', as: :blog_article

  # Subscriptions (beta testing)
  get 'subscriptions/:code' => 'subscriptions#new', as: :subscription
  post 'subscriptions' => 'subscriptions#create'

  # Sign in/out
  get    'login'  => 'session#new',     as: :login
  post   'login'  => 'session#create'
  delete 'logout' => 'session#destroy', as: :logout
  get    'logout' => 'session#destroy'  # temporary for development

  # Registration
  get  'register/:code' => 'registration#new', as: :register
  post 'register/:code' => 'registration#create'

  # Password reset
  get   'reset/:code' => 'password#edit', as: :reset
  put   'reset/:code' => 'password#update'
  patch 'reset/:code' => 'password#update'

  get 'privacy' => 'site#privacy'
  get 'terms'   => 'site#terms'

  root 'site#index'
end

app/models/article.rb
class Article < ActiveRecord::Base
  before_create :set_slug
  mount_uploader :blog_image, BlogImageUploader

  belongs_to :user
  has_many :comments

  validates :title, :body, presence: true
  validates :slug, uniqueness: { case_sensitive: false }

  private

  def set_slug
    i = 2
    s = sn = self.title.downcase.gsub(/\W+/, "-")
    while Article.find_by(slug: sn)
      sn = "#{s}-#{i}"
      i += 1
    end
    self.slug = sn
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :is_admin?
  before_action :get_article, except: [ :index, :new, :create ]

  def index
    @page_title = "Articles"
    @current = []
    @archived = []
    Article.all.each do |article|
      article.is_archived ? @archived.push(article) : @current.push(article)
    end
  end

  def show
    @page_title = "Article"
  end

  def new
    @page_title = "Add a Article"
    @article = Article.new
  end

  def create
    article = Article.new(article_params)
    article.user = current_user
    article.save

    redirect_to article_url(article)
  end

  def edit
    @page_title = "Edit a Article"
  end

  def update
    article = Article.find(params[:id])
    article.update(article_params)
    article.save

    redirect_to params[:return_to_index] ? articles_url : article_url(article)
  end

  def destroy
    if @article.destroy
      flash[:notice] = "Article #{params[:id]} destroyed."
    else
      flash[:alert] = "Failed to destroy Article #{params[:id]}."
    end

    redirect_to articles_url
  end

  private

  def get_article
    unless @article = Article.find( params[:id] )
      redirect_to articles_url, alert: "Can't find Article #{params[:id]}."
    end
  end

  def article_params
    params.require(:article).permit(
      :title,
      :body,
      :blog_image,
      :blog_image_cache,
      :is_archived
    )
  end
end

app/views/articles/_form.html.erb
<div class="col-md-8 col-sm-12">
  <%= form_for @article, :html => { multipart: true } do |f| %>
    <legend>
      <% if @article.persisted? %>
        Update <em><%= @article.title %></em>
      <% else %>
        Add a new article
      <% end %>
    </legend>
    <div class="form-group">
      <%= f.label :title, class: "sr-only" %>
      <%= f.text_field :title, placeholder: "Title", class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :body, class: "sr-only" %>
      <%= f.text_area :body, placeholder: "Add content here (markdown enabled)", class: "form-control", style: "width: 100%; height: 300px" %>
    </div>
    <div class="form-group">
      <%= f.label :blog_image, "Image", class: "sr-only" %>
      <%= f.file_field :blog_image, placeholder: "Upload an image", class: "form-control" %>
      <%= f.hidden_field :blog_image_cache %>
    </div>
    <div class="form-group">
      <%= f.submit class: "btn btn-danger" %>
    </div>
    <div class="form-group">
      <%= image_tag(@article.blog_image_url) if @article.blog_image? %>
    </div>
  <% end %>
</div>

app/views/articles/_table.html.erb
  <div class="table-responsive">
    <table class="table table-striped crud-list">
      <caption class="<%= table_type.downcase %>"><%= table_type %> Articles</caption>
      <% if articles.empty? %>
        <tbody>
          <tr>
            <td>None yet.</td>
          </tr>
        </tbody>
      <% else %>
        <thead>
          <tr>
            <th>Title</th>
            <th>Slug</th>
            <th>Author</th>
            <th>Published</th>
            <th class="three-controls">&nbsp;</th>
          </tr>
        </thead>
        <tbody>
          <% articles.each do |article| %>
            <tr>
              <td class="article-title"><%= link_to article.title, article_url(article), title: "To the article" %></td>
              <td><%= link_to article.slug, blog_article_url(article.slug), title: "To the post" %></td>
              <td><%= link_to article.user.username, user_url(article.user), title: "To the user" %></td>
              <td><%= article.created_at.to_formatted_s(:created_at) %></td>
              <td class="controls">
                <%= link_to "Edit", edit_article_url(article), class: "btn btn-success btn-xs" %>
                <%= form_for article, html: { class: "inline" } do |f| %>
                  <input type="hidden" name="return_to_index" value="true">
                  <%= f.hidden_field :is_archived, value: (!article.is_archived) %>
                  <% text = article.is_archived ? "Unarchive" : "Archive" %>
                  <%= f.submit text, class: "btn btn-warning btn-xs" %>
                <% end %>
                <%= link_to "Delete", article_url(article), method: :destroy, class: "btn btn-danger btn-xs" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      <% end %>
    </table>
  </div>

app/views/articles/edit.html.erb
<%= render partial: "form" %>

app/views/articles/index.html.erb
<h2 class="sub-header">
  Articles
  <span class="pull-right">
    <%= link_to "New Article", new_article_url, class: "btn btn-success btn-xs" %>
  </span>
</h2>

<%= render partial: 'table', locals: { table_type: 'Current', articles: @current } %>

<%= render partial: 'table', locals: { table_type: 'Archived', articles: @archived } %>

app/views/articles/new.html.erb
<%= render partial: "form" %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<dl>
  <dt>Slug</dt>
  <dd><%= @article.slug %></dd>
  <dt>Author</dt>
  <dd><%= @article.user.username %></dd>
  <dt>Body</dt>
  <dd>
    <%= m(@article.body) %>
  </dd>
  <dt>Published</dt>
  <dd><%= @article.created_at.strftime("%-I:%M on %a, %-d %b %Y") %></dd>
  <dt>Archived?</dt>
  <dd><%= boolean_to_yesno( @article.is_archived ) %></dd>
  <dt>Image</dt>
  <dd><img src="<%= @article.blog_image %>" alt="<%= @article.blog_image %>"></dd>
</dl>

<p>
  <%= link_to "All articles", articles_url %> |
  <%= link_to "Edit <em>#{@article.title}</em>".html_safe, edit_article_url( @article ) %> |
  <%= link_to "Delete <em>#{@article.title}</em>".html_safe, article_url, method: :delete %>
</p>