config/routes.rb
Wh::Application.routes.draw do

  scope :admin do
    get 'overview' => 'dashboard#index', as: :dashboard

    resources :subscribers, only: [ :index, :destroy ]
    resources :registrants, only: [ :index, :destroy ]
    resources :organizations
    resources :users
    resources :profiles
    resources :affiliations
    resources :contacts
    resources :articles
  end

  # Blog

  get 'blog' => 'blog#index', as: :blog
  get 'blog/:slug' => 'blog#show', as: :blog_article

  # Subscriptions (beta testing)
  get 'subscriptions/:code' => 'subscriptions#new', as: :subscription
  post 'subscriptions' => 'subscriptions#create'

  # Sign in/out
  get    'login'  => 'session#new',     as: :login
  post   'login'  => 'session#create'
  delete 'logout' => 'session#destroy', as: :logout
  get    'logout' => 'session#destroy'  # temporary for development

  # Registration
  get  'register/:code' => 'registration#new', as: :register
  post 'register/:code' => 'registration#create'

  # Password reset
  get   'reset/:code' => 'password#edit', as: :reset
  put   'reset/:code' => 'password#update'
  patch 'reset/:code' => 'password#update'

  get 'privacy' => 'site#privacy'
  get 'terms'   => 'site#terms'

  root 'site#index'
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  before_action :set_csrf_token_header, only: [ :index ]

  def index
  end

  def privacy
    render layout: 'layouts/blog'
  end

  def terms
    render layout: 'layouts/blog'
  end
end

app/views/site/_about_us.html.erb
<article id="about-us" class="about-us">
  <div class="container">
    <header class="row">
      <div class="col-md-12">
        <h2>How it all started</h2>
      </div>
    </header>
    <div class="row">
      <aside class="col-md-12">
        <p>
          <strong>W Hub</strong> was born around a cup of coffee, plenty of energy,
          and lots of questions!
        </p>
        <p>
          Why are so many talented people unable to find a job? Why are so many great
          business ideas unexplored just because the right partner to bounce them off
          of is lacking? Why are so many startups struggling to find the right people
          to help develop their business?
        </p>
        <p>
          There are so many talents, ideas, and entrepreneurs in this Hong Kong
          Hub&mdash;it is time to bring them together to <strong>make a difference</strong>
          in the startup ecosystem!
        </p>
        <p>
        <p>
          Welcome to the Whubbers community!
        </p>
      </aside>
    </div>
  </div>
</article>

app/views/site/_about_you.html.erb
<article id="about-you" class="about-you">
  <div class="container">
    <header class="row">
      <div class="col-md-12 about-you-head">
        <p>
          We're a community for talented, professional co-founders,
          job seekers, and entrepreneurs.
        </p>
        <h2>You are...</h2>
      </div>
    </header>
    <div class="row">
      <aside class="col-md-4">
        <div>
          <header>
            <div class="about-icon about-startup">
              <i class="fa fa-eye"></i>
            </div>
            <h3 class="about-startup">A STARTUP</h3>
          </header>
          <ul class="user-benefits">
            <li>
              <i class="fa fa-bolt"></i> Find talented designers, technical gurus,
              and business experts
            </li>
            <li>
              <i class="fa fa-comment-o"></i> Showcase your startups and share your passion
            </li>
            <li>
              <i class="fa fa-group"></i> Become part of the community and
              <span class="startup-style"><strong>meet the Whubbers</strong></span>
            </li>
          </ul>
        </div>
      </aside>
      <aside class="col-md-4">
        <div>
          <header>
            <div class="about-icon about-talent">
              <i class="fa fa-table"></i>
            </div>
            <h3 class="about-talent">TALENT</h3>
          </header>
          <ul class="user-benefits">
            <li>
              <i class="fa fa-rocket"></i> Make a difference!
            </li>
            <li>
              <i class="fa fa-gears"></i> Take advantage of a startup's
              flexibility, excitement, and entrepreneurial spirit
            </li>
            <li>
              <i class="fa fa-tachometer"></i>
              <span class="talent-style"><strong>Get a job doing work you actually care about</strong></span>
            </li>
          </ul>
        </div>
      </aside>
      <aside class="col-md-4">
        <div>
          <header>
            <div class="about-icon about-curious">
              <i class="fa fa-pencil"></i>
            </div>
            <h3 class="about-curious">CURIOUS</h3>
          </header>
          <ul class="user-benefits">
            <li>
              <i class="fa fa-lightbulb-o"></i> Learn more about the startup ecosystem
            </li>
            <li>
              <i class="fa fa-road"></i> Consider an exciting new career path
            </li>
            <li>
              <i class="fa fa-thumb-tack"></i> Subscribe to our newsletter and
              <span class="generic-style"><strong>become a Whubber</strong></span>
            </li>
          </ul>
        </div>
      </aside>
    </div>
  </div>
</article>

app/views/site/_contact_us.html.erb
<article id="contact-us" class="container contact-us">
  <header class="row">
    <div class="col-md-12">
      <h2>Contact us</h2>
    </div>
  </header>
  <section class="row">
    <div class="col-md-8 col-md-offset-2">
      <form accept-charset="UTF-8" action="<%= contacts_url %>" id="contact-form" method="post">
        <fieldset>
          <legend>Want to know more? We'd love to hear from you!</legend>
          <div class="contact error-message"></div>
          <div class="input-group">
            <label for="contact-email" class="sr-only">Email</label>
            <input type="email" id="contact-email" name="email" placeholder="Email..." class="form-control" required>
          </div>
          <div class="input-group">
            <label for="contact-subject" class="sr-only">Subject</label>
            <input type="text" id="contact-subject" name="subject" placeholder="Subject..." class="form-control" required>
          </div>
          <div class="input-group">
            <label for="contact-message" class="sr-only">Message</label>
            <textarea id="contact-message" name="message" placeholder="Message..." class="form-control"></textarea>
          </div>
          <div class="input-group">
            <input type="submit" name="commit" value="Send" class="btn">
            <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
          </div>
        </fieldset>
      </form>
      <div class="contact success-message"></div>
    </div>
  </section>
</article>

app/views/site/_countdown.html.erb
<article id="countdown" class="countdown">
  <div class="container">
    <div class="row">
      <div class="col-md-12 countdown-block">
        <header class="logo">
          <img src="/assets/logo/whub_logo_04.png" alt="W Hub">
        </header>
        <h1>Uniting startups and talent</h1>
        <p>
          Find a job in a startup or co-found one!
          <br>
          Countdown to our debut:
        </p>
        <section id="countdown-timer" class="timer">
          <div class="days-wrapper">
            <span id="days" class="days"></span>
            <br>
            days
          </div>
          <div class="hours-wrapper">
            <span id="hours" class="hours"></span>
            <br>
            hours
          </div>
          <div class="minutes-wrapper">
            <span id="minutes" class="minutes"></span>
            <br>
            minutes
          </div>
          <div class="seconds-wrapper">
            <span id="seconds" class="seconds"></span>
            <br>
            seconds
          </div>
        </section>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <p class="top-arrow" id="countdown-arrow">
          <i class="fa fa-chevron-down"></i>
        </p>
      </div>
    </div>
  </div>
</article>

app/views/site/_navigation.html.erb
<div class="container">
  <nav class="row">
    <div class="col-sm-2 col-xs-12">
      <a class="menu-countdown" href="#">Countdown</a>
    </div>
    <div class="col-sm-2 col-xs-12">
      <a class="menu-subscribe" href="#">Sign up now!</a>
    </div>
    <div class="col-sm-2 col-xs-12">
      <a class="menu-about-you" href="#">About you</a>
    </div>
    <div class="col-sm-2 col-xs-12">
      <a class="menu-testimonials" href="#">Testimonials</a>
    </div>
    <div class="col-sm-2 col-xs-12">
      <a class="menu-about-us" href="#">About us</a>
    </div>
    <div class="col-sm-2 col-xs-12">
      <a class="menu-contact-us" href="#">Contact us</a>
    </div>
    <div class="hide-menu">
      <a href="#" data-placement="bottom" data-original-title="Hide menu">
        <i class="fa fa-bars"></i>
      </a>
    </div>
  </nav>
</div>
<div class="show-menu">
  <a href="#" data-toggle="tooltip" data-placement="bottom" data-original-title="Show menu">
    <i class="fa fa-bars"></i>
  </a>
</div>

app/views/site/_register.html.erb
<article id="register" class="container">
  <div class="row">
    <div class="col-md-12 register">
      <header>
        <h2>
          Don't miss out!
          <br><br>
          <span class="color-orange">Sign up now</span> to get a place for our private beta version</h2>
          <br>
      </header>
      <form accept-charset="UTF-8" action="<%= login_url %>" id="registration-form" method="post" class="form-inline">
        <div class="row">
          <div class="col-lg-8 col-md-6 col-sm-6 col-xs-12">
            <label for="user_email" class="sr-only">Email</label>
            <input type="email" id="user_email" name="email" placeholder="Enter your email address..." class="form-control" required>
          </div>
          <div class="col-lg-2 col-md-3 col-sm-3 col-xs-12 color-green">
            <input type="submit" id="talent_submit" name="talent" value="I am talent" class="btn">
          </div>
          <div class="col-lg-2 col-md-3 col-sm-3 col-xs-12 color-blue">
            <input type="submit" id="startup_submit" name="startup" value="I am a startup" class="btn">
            <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
          </div>
        </div>
      </form>
      <div class="registration success-message"></div>
      <div class="registration error-message"></div>
    </div>
  </div>
</article>

app/views/site/_registration_form.html.erb
<div class="container">
  <div class="row">
    <div class="span12 register">
      <h3>Don't miss out!</h3>
      <%= form_for :user, url: login_url, html: { class: "form-inline" } do |f| %>
        <%= f.email_field :email, placeholder: "Enter your email..." %>
        <%= f.hidden_field :is_startup, value: false %>
        <%= f.submit "I'm a startup", id: "startup_submit", class: "btn", name: "startup" %>
        <%= f.submit "I am talent", id: "talent_submit", class: "btn", name: "talent" %>
      <% end %>
      <div class="success-message"></div>
      <div class="error-message"></div>
    </div>
  </div>
</div>

app/views/site/_social_media.html.erb
<div class="social-media">
  <ul>
    <li>
      <a class="ultm ultm-facebook ultm-48 ultm-square" href="https://www.facebook.com/whubhk" target="_blank"></a>
    </li>
    <li>
      <a class="ultm ultm-twitter ultm-48 ultm-square" href="https://twitter.com/WHubhk" target="_blank"></a>
    </li>
  </ul>
</div>

app/views/site/_subscribe.html.erb
<article id="subscribe" class="container">
  <div class="row">
    <div class="col-md-12 subscribe">
      <header>
        <h2>Don't miss out!</h2>
        <p>
          <span class="generic-style">Sign up now</span> to take part in our private beta testing.
        </p>
      </header>
      <form accept-charset="UTF-8" action="<%= subscriptions_url %>" id="subscription-form" method="post" class="form-inline">
        <div class="row">
          <div class="col-lg-9 col-md-8 col-sm-8 col-xs-12">
            <label for="subscriber-email" class="sr-only">Email</label>
            <input type="email" id="subscriber-email" name="email" placeholder="Enter your email address..." class="form-control" required>
          </div>
          <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12 talent-style">
            <input type="submit" id="subscriber-submit" name="talent" value="Sign up now!" class="btn">
            <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
          </div>
        </div>
      </form>
      <div class="subscription success-message"></div>
      <div class="subscription error-message"></div>
    </div>
  </div>
</article>

app/views/site/_testimonials.html.erb
<article id="testimonials">
  <div class="container">
    <div class="row">
      <div class="col-md-12 testimonials">
        <header>
          <h2>Some of our awesome <span class="startup-style"><strong>startup partners</strong></span></h2>
        </header>
        <br>
        <br>
        <!-- <div class="testimonial-active"></div> -->
        <!-- <div class="testimonial-quote">&ldquo; &rdquo;</div> -->
        <!-- HK Hacknight -->
        <div class="testimonial-single">
          <div class="testimonial-single-image">
            <a href="https://http://www.hongkonghacknights.com/" target="_blank" style="width: 110%">
              <img src="assets/clients/hkhacknights-logo.png" alt="">
            </a>
          </div>
        </div>
        <!-- Mabogo -->
        <div class="testimonial-single">
          <div class="testimonial-single-image">
            <a href="http://www.mabogo.com" target="_blank">
              <img src="assets/clients/mabogo-logo.png" alt="">
            </a>
          </div>
        </div>
        <!-- General assembly -->
        <div class="testimonial-single">
          <div class="testimonial-single-image">
            <a href="https://generalassemb.ly/hong-kong" target="_blank">
              <img src="assets/clients/ga-logo.png" alt="">
            </a>
          </div>
        </div>
        <!-- MesAnges -->
        <div class="testimonial-single">
          <div class="testimonial-single-image">
            <img src="assets/clients/mesanges-logo.jpg" alt="">
          </div>
        </div>
        <!-- Evobilis -->
        <div class="testimonial-single">
          <div class="testimonial-single-image">
            <a href="http://www.evobilis.com/" target="_blank">
              <img src="assets/clients/evobilis-logo.jpg" alt="">
            </a>
          </div>
        </div>
        <!-- Ekowarehouse -->
        <div class="testimonial-single">
          <div class="testimonial-single-image">
            <a href="http://ekowarehouse.com" target="_blank">
              <img src="assets/clients/ekowarehouse-logo.jpg" alt="">
            </a>
          </div>
        </div>
        <!-- Makible -->
        <div class="testimonial-single">
          <div class="testimonial-single-image">
            <a href="https://store.makibox.com/" target="_blank">
              <img src="assets/clients/makible-logo.png" alt="">
            </a>
          </div>
        </div>
        <!-- Quantifeed -->
        <div class="testimonial-single">
          <div class="testimonial-single-image">
            <a href="http://www.quantifeed.com/" target="_blank">
              <img src="assets/clients/quantifeed-logo.png" alt="">
            </a>
          </div>
        </div>
        <!-- Kids Dailies -->
        <div class="testimonial-single">
          <div class="testimonial-single-image">
            <a href="http://www.daily7-daily10.com" target="_blank">
              <img src="assets/clients/kids-dailies-logo.png" alt="">
            </a>
          </div>
        </div>
        <!-- BitGame Labs -->
        <div class="testimonial-single">
          <div class="testimonial-single-image">
            <a href="http://bitgamelabs.com/" target="_blank">
              <img src="assets/clients/bitgame-labs-logo.png" alt="">
            </a>
          </div>
        </div>
        <!-- Sol Wellness -->
        <div class="testimonial-single">
          <div class="testimonial-single-image">
            <a href="http://www.sol-wellness.com/" target="_blank">
              <img src="assets/clients/solwellness-logo.png" alt="">
            </a>
          </div>
        </div>
        <!-- Mary J -->
        <div class="testimonial-single">
          <div class="testimonial-single-image">
            <a href="http://www.mmheshop.com/" target="_blank">
              <img src="assets/clients/maryj-logo.png" alt="" style="width: 70%">
            </a>
          </div>
        </div>
        <!-- BuyMeDesign -->
        <div class="testimonial-single">
          <div class="testimonial-single-image">
            <a href="http://www.buymedesign.com/" target="_blank">
              <img src="assets/clients/buymedesign-logo.png" alt="">
            </a>
          </div>
        </div>
        <!-- Hong Kong inside Feng shui -->
        <div class="testimonial-single">
          <div class="testimonial-single-image">
            <a href="http://www.hongkonginside.com" target="_blank">
              <img src="assets/clients/hki-logo.png" alt="">
            </a>
          </div>
        </div>
        <!-- Naku -->
        <div class="testimonial-single">
          <div class="testimonial-single-image">
            <a href="http://www.nakuwine.com/" target="_blank">
              <img src="assets/clients/naku-logo.jpg" alt="">
            </a>
          </div>
        </div>
        <!-- First code academy -->
        <div class="testimonial-single">
          <div class="testimonial-single-image">
            <a href="http://firstcodeacademy.com/" target="_blank">
              <img src="assets/clients/first-code-academy-logo.png" alt="" style="width: 70%">
            </a>
          </div>
        </div>
        <!-- Nayla slippers -->
        <div class="testimonial-single">
          <div class="testimonial-single-image">
            <a href="http://www.nayla-slippers.com/" target="_blank">
              <img src="assets/clients/nayla-slippers-logo.png" alt="">
            </a>
          </div>
        </div>
        <!-- Spacious -->
        <div class="testimonial-single">
          <div class="testimonial-single-image">
            <a href="http://www.spacious.hk/" target="_blank">
              <img src="assets/clients/spacious-logo.jpg" alt="" style="width: 70%">
            </a>
          </div>
        </div>
        

      </div>
    </div>
  </div>
</article>

app/views/site/index.html.erb
<header role="banner">
  <%= render partial: "navigation" %>
</header>
<%= render partial: "social_media" %>
<%= render partial: "countdown" %>
<%= render partial: "subscribe" %>
<%= render partial: "about_you" %>
<%= render partial: "testimonials" %>
<%= render partial: "about_us" %>
<%= render partial: "contact_us" %>

app/views/site/privacy.html.erb
<h1>Privacy policy</h1>

app/views/site/terms.html.erb
<h1>Terms of use</h1>