config/routes.rb
Wh::Application.routes.draw do

  scope :admin do
    get 'overview' => 'dashboard#index', as: :dashboard

    resources :subscribers, only: [ :index, :destroy ]
    resources :registrants, only: [ :index, :destroy ]
    resources :organizations
    resources :users
    resources :profiles
    resources :affiliations
    resources :contacts
    resources :articles
  end

  # Blog

  get 'blog' => 'blog#index', as: :blog
  get 'blog/:slug' => 'blog#show', as: :blog_article

  # Subscriptions (beta testing)
  get 'subscriptions/:code' => 'subscriptions#new', as: :subscription
  post 'subscriptions' => 'subscriptions#create'

  # Sign in/out
  get    'login'  => 'session#new',     as: :login
  post   'login'  => 'session#create'
  delete 'logout' => 'session#destroy', as: :logout
  get    'logout' => 'session#destroy'  # temporary for development

  # Registration
  get  'register/:code' => 'registration#new', as: :register
  post 'register/:code' => 'registration#create'

  # Password reset
  get   'reset/:code' => 'password#edit', as: :reset
  put   'reset/:code' => 'password#update'
  patch 'reset/:code' => 'password#update'

  get 'privacy' => 'site#privacy'
  get 'terms'   => 'site#terms'

  root 'site#index'
end

app/models/subscriber.rb
class Subscriber < ActiveRecord::Base
  TIME_TO_EXPIRE = 1.week

  before_create :set_code
  before_save :downcase_email
  before_save :set_expiration

  validates :email, presence: true
  validates :email, format: { with: /\A[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\Z/i }

  def self.find_by_code(code)
    clean_up
    if subscriber = Subscriber.where('code = ?', code).take
      subscriber.save!
      return subscriber
    end
    nil
  end

  def set_expiration
    self.expires_at = TIME_TO_EXPIRE.from_now
  end

  def self.clean_up
    Subscriber.where('expires_at < ?', Time.now.gmtime).destroy_all
  end

  protected

  def set_code
    self.code = SecureRandom.urlsafe_base64
  end

  def downcase_email
    self.email.downcase!
  end
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  before_action :is_admin?
  before_action :get_subscriber, except: [ :index ]

  def index
    @page_title = "Subscribers"
    @subscribers = Subscriber.all
    @now = Time.now.gmtime
  end

  def destroy
    if @subscriber.destroy
      flash[:notice] = "Subscriber #{params[:id]} destroyed."
    else
      flash[:alert] = "Failed to destroy Subscriber #{params[:id]}."
    end

    redirect_to subscribers_url
  end

  private

  def get_subscriber
    unless @subscriber = Subscriber.find( params[:id] )
      redirect_to subscribers_url, alert: "Can't find Subscriber #{params[:id]}."
    end
  end

  def subscriber_params
    params.require(:subscriber).permit( :email )
  end
end

app/views/subscribers/_form.html.erb
<div class="col-md-4 col-md-offset-4 col-sm-12">
  <%= form_for @user do |f| %>
    <legend><% if @user.persisted? %>Update <%= @user.username %><% else %>Add a new user<% end %></legend>
    <div class="form-group">
      <%= f.label :username, class: "sr-only" %>
      <%= f.text_field :username, placeholder: "Username", class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :email, class: "sr-only" %>
      <%= f.email_field :email, placeholder: "Email", class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.submit class: "btn btn-danger" %>
    </div>
  <% end %>
</div>

app/views/subscribers/index.html.erb
<h2 class="sub-header">Subscribers</h2>

<% if @subscribers.empty? %>
  <p>No subscribers yet.</p>
<% else %>
  <div class="table-responsive">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Email</th>
          <th>Validated?</th>
          <th class="controls">&nbsp;</th>
        </tr>
      </thead>
      <tbody>
        <% @subscribers.each do |subscriber| %>
          <tr>
            <td><a href="mailto:<%= subscriber.email %>" title="Send mail"><%= subscriber.email %></a></td>
            <td>
              <% if subscriber.expires_at && subscriber.expires_at < @now %>
                <strong class="expired">Expired</strong>
              <% else %>
                <%= boolean_to_yesno( subscriber.code.blank? ) %>
              <% end %>
            </td>
            <td class="controls">
              <%= link_to "Delete", subscriber_url(subscriber), method: :destroy, class: "btn btn-danger btn-xs" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/subscribers/show.html.erb
<h1><%= @user.username %></h1>

<dl>
  <dt>Email address</dt>
  <dd><%= @user.email %></dd>
  <dt>Profiles</dt>
  <dd>
    <% if @user.profiles.empty? %>
      No profiles yet!
    <% else %>
      <ul>
        <% @user.profiles.each do |profile| %>
          <li><%= link_to profile.name, profile_url(profile) %></li>
        <% end %>
      </ul>
    <% end %>
  </dd>
  <dt>Joined</dt>
  <dd><%= @user.created_at.strftime("%-I:%M on %a, %-d %b %Y") %></dd>
  <dt>Active?</dt>
  <dd><%= boolean_to_yesno( @user.is_active ) %></dd>
  <dt>Admin?</dt>
  <dd><%= boolean_to_yesno( @user.is_admin ) %></dd>
  <dt>Contacts</dt>
  <dd>
    <% if @user.contacts.empty? %>
      None yet.
    <% else %>
      <ol reversed>
        <% @user.contacts.order("created_at desc").each do |contact| %>
          <li><%= link_to contact.subject, contact_url(contact) %></li>
        <% end %>
      </ol>
    <% end %>
  </dd>
</dl>

<p>
  <%= link_to "All users", users_url %> |
  <%= link_to "Edit #{@user.username}", edit_user_url( @user ) %> |
  <%= link_to "Delete #{@user.username}", user_url, method: :destroy, confirm: "Are you sure?" %>
</p>